" .vimrc file by Ke Cheung

let vimrc_bundles = "~/.vim/vimrc.bundles"
if filereadable(expand(vimrc_bundles))
  execute 'source' vimrc_bundles
endif

" Automatic reloading of .vimrc
autocmd! bufwritepost .vimrc source %

syntax enable
syntax on

set encoding=utf-8 nobomb
set number
set autoindent
set autoread
set mouse=a
set hidden
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set backspace=indent,eol,start
set ruler
set dictionary+=/usr/share/dict/words
set isk+=-

" 定义快捷键的前缀，即<Leader>
let mapleader = ";"

" Shortcut to rapidly toggle `set list`
set listchars=tab:▸\ ,trail:-,eol:¬,extends:>,precedes:<
nmap <leader>l :set list!<CR>

" Fast saving
nmap <leader>w :w!<cr>

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

map <leader>tb :new tab<CR>
map <leader>tc :tab close<CR>
map <leader>to :tab only<CR>
map <leader>tm :tab move<CR>
map <leader>te :new tab edit<CR>

" format json
map <leader>fj <Esc>:%!python -m json.tool<CR>

filetype indent on
autocmd FileType html setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=0
autocmd FileType coffee,javascript setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType sass,scss,css setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType java setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType python setlocal expandtab smarttab shiftwidth=4 tabstop=4 softtabstop=4 textwidth=79
autocmd FileType ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType php setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120

colorscheme solarized
