" .vimrc file by Ke Cheung

" Automatic reloading of .vimrc
autocmd! bufwritepost .vimrc source %

syntax enable
syntax on

set encoding=utf-8 nobomb
set number
set autoindent
set autoread
set mouse=a
set hidden
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set backspace=indent,eol,start
set ruler
set dictionary+=/usr/share/dict/words
set isk+=-

let mapleader = ','

" Shortcut to rapidly toggle `set list`
set listchars=tab:▸\ ,trail:-,eol:¬,extends:>,precedes:<
nmap <leader>l :set list!<CR>

" Fast saving
nmap <leader>w :w!<cr>

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

map <leader>tb :new tab<CR>
map <leader>tc :tab close<CR>
map <leader>to :tab only<CR>
map <leader>tm :tab move<CR>
map <leader>te :new tab edit<CR>

" format json
map <leader>fj <Esc>:%!python -m json.tool<CR>


"    Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

"    fugitive
Plugin 'tpope/vim-fugitive'

"    solarized
Plugin 'altercation/vim-colors-solarized'
if has('gui_running')
    set background=light
else
    set background=dark
endif

"    ctrlp
Plugin 'kien/ctrlp.vim'

"    nerdtred
Plugin 'scrooloose/nerdtree'
map <leader>n :NERDTreeToggle<CR>

"    syntastic
Plugin 'scrooloose/syntastic'
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"    'hynek/vim-python-pep8-indent'
Plugin 'hynek/vim-python-pep8-indent'

"    vim-better-whitespace
Plugin 'ntpeters/vim-better-whitespace'

"    vim-trailing-whitespace
Plugin 'bronson/vim-trailing-whitespace'
map <leader><Space> :FixWhitespace<CR>

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

filetype indent on
autocmd FileType html setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=0
autocmd FileType coffee,javascript setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType sass,scss,css setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType java setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType python setlocal expandtab smarttab shiftwidth=4 tabstop=4 softtabstop=4 textwidth=79
autocmd FileType ruby setlocal tabstop=2 shiftwidth=2 softtabstop=2 textwidth=120
autocmd FileType php setlocal tabstop=4 shiftwidth=4 softtabstop=4 textwidth=120

colorscheme solarized
